# Generated by Django 4.1 on 2022-09-21 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0004_alter_mywatchlist_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mywatchlist',
            old_name='release_date',
            new_name='release',
        ),
    ]
