# Generated by Django 4.1 on 2022-09-21 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0005_rename_release_date_mywatchlist_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mywatchlist',
            name='release',
        ),
    ]
